name: squeeze-nba
channels:
  - conda-forge
  - defaults
dependencies:
  - python~=3.14
  - great_tables
  - jupyter
  - matplotlib
  - polars
  - pyjanitor
  - scipy
  - pip:
    - gt-extras
    - nba_api